/* ============================================================
   OpenAPI 3.1 for /v1 — served at GET /v1/openapi.json (public) and rendered by the
   developer portal. The SDKs are generated from this document (sdk/), so a route that is
   not here does not exist for customers. Keep the examples runnable against the sandbox.
   ============================================================ */
import { EVENT_TYPES } from "../core/platform/mapping.js";
import { SCENARIO_NUMBERS } from "../core/platform/sandbox.js";

const money = (desc: string) => ({ type: "object", description: desc, properties: { amount: { type: "string", example: "5000" }, currency: { type: "string", example: "XAF" } }, required: ["amount", "currency"] });
const err = (code: string, message: string) => ({ error: { code, message, details: {} }, meta: { request_id: "req_5f1c9e2ab3d94c7e" } });

export function openApiV1(baseUrl: string) {
  const live = `${baseUrl.replace(/\/$/, "")}/v1`;
  const sandbox = `${(process.env.SANDBOX_API_URL ?? "https://sandbox.api.momome.xyz").replace(/\/$/, "")}/v1`;
  return {
    openapi: "3.1.0",
    info: {
      title: "MoMo›Me API", version: "1.0.0",
      summary: "Bitcoin, Lightning and stablecoin payouts into African Mobile Money.",
      description: [
        "One API to turn digital value into local-currency Mobile Money. The integration is three steps: **create a quote** (locks the rate and the fees), **create a payment** from it (returns the instruction your customer pays — a Lightning invoice or an address), then **listen to the webhook** (`payment.completed`) or poll `GET /payments/{id}`.",
        "", "Every response is `{ data, meta }` or `{ error: { code, message, details }, meta }`; `meta.request_id` is safe to quote to support.",
        "", "**Environments.** `mm_test_…` credentials work only against the sandbox base URL, `mm_live_…` only against production; the wrong one answers `401 environment_mismatch` with the right `base_url` in `details`.",
        "", "**Idempotency.** Every `POST` that creates or changes something requires an `Idempotency-Key` header. Retrying with the same key and body returns the original response (`Idempotent-Replayed: true`); the same key with a different body is refused (`409 idempotency_key_reused`).",
        "", "**Rate limits.** Per organization and plan (`X-RateLimit-Limit`, `X-RateLimit-Remaining`; `429` carries `Retry-After`). Payment endpoints have a stricter ceiling.",
      ].join("\n"),
      contact: { name: "MoMo›Me developers", url: "https://www.momome.xyz/developers", email: "developers@momome.xyz" },
    },
    servers: [{ url: live, description: "Production (mm_live_ credentials)" }, { url: sandbox, description: "Sandbox (mm_test_ credentials)" }],
    security: [{ bearerAuth: [] }],
    tags: [
      { name: "Quotes", description: "Lock a rate and the fees for a destination amount (or a source amount)." },
      { name: "Payments", description: "Create, track, cancel, retry and refund payments." },
      { name: "Recipients", description: "Validate a Mobile Money number and its registered name." },
      { name: "Webhooks", description: "Endpoints that receive signed events." },
      { name: "Settlements", description: "Pay out an organization balance." },
      { name: "Account", description: "Your organization, credential, plan, balances and usage." },
      { name: "Transactions", description: "The unified timeline of a payment." },
      { name: "Sandbox", description: "Test-environment helpers." },
      { name: "Identities", description: "MoMo›Me Connect: payment identities, aliases, counterparties, reachability." },
      { name: "Payment intents", description: "MoMo›Me Connect: the canonical intent — internal ledger route or funding instruction." },
      { name: "Invoices", description: "MoMo›Me Connect: invoices, payment links, QR, request-to-pay." },
      { name: "Payouts", description: "MoMo›Me Connect: from a balance to Mobile Money or a Lightning Address." },
      { name: "Checkout", description: "MoMo›Me Connect: the hosted checkout's public endpoints." },
      { name: "Health" },
    ],
    paths: {
      "/quotes": { post: { tags: ["Quotes"], operationId: "createQuote", summary: "Create a quote", parameters: [idemParam()], requestBody: body("QuoteRequest", { source: { asset: "BTC", network: "LIGHTNING" }, destination: { country: "CM", currency: "XAF", amount: "5000", phone: "+237670123456" } }), responses: { "201": resp("Quote"), "422": errResp("validation_failed | asset_unsupported | network_unsupported | country_unsupported | amount_out_of_range"), "503": errResp("provider_unavailable | service_paused") } } },
      "/quotes/{id}": { get: { tags: ["Quotes"], operationId: "getQuote", summary: "Retrieve a quote", parameters: [idParam("quote")], responses: { "200": resp("Quote"), "404": errResp("quote_not_found") } } },
      "/payments": {
        post: { tags: ["Payments"], operationId: "createPayment", summary: "Create a payment from a quote", parameters: [idemParam()], requestBody: body("PaymentRequest", { quote_id: "q_mubsrd95gi3elw", reference: "ORDER-12345", recipient: { phone: "+237670123456", name: "Nana Jean Paul" }, metadata: { order_id: "12345" } }), responses: { "201": resp("Payment"), "404": errResp("quote_not_found"), "409": errResp("quote_already_used | recipient_unverified (details.confirmation_token) | validation_failed (duplicate reference)"), "410": errResp("quote_expired"), "422": errResp("recipient_invalid | recipient_reserved | limit_exceeded"), "403": errResp("compliance_blocked"), "503": errResp("insufficient_liquidity | provider_unavailable") } },
        get: { tags: ["Payments"], operationId: "listPayments", summary: "List payments", parameters: [q("limit", "integer", "1–100, default 25"), q("status", "string", "Filter by status"), q("reference", "string", "Your reference"), q("created_after", "string", "ISO-8601"), q("starting_after", "string", "Cursor: the last id of the previous page")], responses: { "200": listResp("Payment") } },
      },
      "/payments/{id}": { get: { tags: ["Payments"], operationId: "getPayment", summary: "Retrieve a payment", description: "Add `?wait=25&status=AWAITING_PAYMENT` to long-poll: the response returns as soon as the status changes from the one you hold (or after `wait` seconds).", parameters: [idParam("payment"), q("wait", "integer", "Seconds to hold the request for a change (0–30)"), q("status", "string", "The status you already hold")], responses: { "200": resp("Payment"), "404": errResp("payment_not_found") } } },
      "/payments/{id}/cancel": { post: { tags: ["Payments"], operationId: "cancelPayment", summary: "Cancel an unpaid payment", parameters: [idParam("payment"), idemParam()], responses: { "200": resp("Payment"), "409": errResp("payment_not_cancellable") } } },
      "/payments/{id}/refund": { post: { tags: ["Payments"], operationId: "refundPayment", summary: "Refund a payment awaiting refund", description: "MoMo›Me settles pass-through: a COMPLETED payment is at the recipient and cannot be reversed. A payment whose payout could not be delivered is `REFUNDED` with `refund.status = awaiting_destination`; give a Lightning invoice here and the funds are returned over Lightning.", parameters: [idParam("payment"), idemParam()], requestBody: body("RefundRequest", { destination: { asset: "BTC", network: "LIGHTNING", invoice: "lnbc…" } }), responses: { "200": resp("Payment"), "409": errResp("payment_not_refundable"), "422": errResp("validation_failed") } } },
      "/payments/{id}/retry": { post: { tags: ["Payments"], operationId: "retryPayment", summary: "Retry the payout", description: "For a payment awaiting refund after a failed payout: ask the engine to deliver again (another provider, or the same one now that it is back).", parameters: [idParam("payment"), idemParam()], responses: { "200": resp("Payment"), "409": errResp("validation_failed") } } },
      "/recipients/validate": { post: { tags: ["Recipients"], operationId: "validateRecipient", summary: "Validate a Mobile Money number", requestBody: body("RecipientValidateRequest", { phone: "+237670123456", name: "Nana Jean Paul" }), responses: { "200": resp("RecipientValidation"), "429": errResp("rate_limited") } } },
      "/webhooks": {
        post: { tags: ["Webhooks"], operationId: "createWebhook", summary: "Register an endpoint", parameters: [idemParam()], requestBody: body("WebhookRequest", { url: "https://example.com/momome/webhook", events: ["payment.completed", "payment.failed", "payment.refunded"], description: "Orders service" }), responses: { "201": resp("WebhookEndpointWithSecret"), "422": errResp("webhook_url_invalid"), "409": errResp("webhook_limit") } },
        get: { tags: ["Webhooks"], operationId: "listWebhooks", summary: "List endpoints", responses: { "200": listResp("WebhookEndpoint") } },
      },
      "/webhooks/{id}": {
        get: { tags: ["Webhooks"], operationId: "getWebhook", summary: "Retrieve an endpoint (with recent deliveries)", parameters: [idParam("webhook endpoint")], responses: { "200": resp("WebhookEndpoint"), "404": errResp("webhook_not_found") } },
        patch: { tags: ["Webhooks"], operationId: "updateWebhook", summary: "Update an endpoint", parameters: [idParam("webhook endpoint")], requestBody: body("WebhookPatch", { enabled: true, events: ["*"] }), responses: { "200": resp("WebhookEndpoint") } },
        delete: { tags: ["Webhooks"], operationId: "deleteWebhook", summary: "Delete an endpoint", parameters: [idParam("webhook endpoint")], responses: { "200": resp("Deleted") } },
      },
      "/webhooks/{id}/test": { post: { tags: ["Webhooks"], operationId: "testWebhook", summary: "Send a ping event now", parameters: [idParam("webhook endpoint")], responses: { "200": resp("Sent") } } },
      "/webhooks/{id}/replay": { post: { tags: ["Webhooks"], operationId: "replayWebhook", summary: "Re-deliver a past event", parameters: [idParam("webhook endpoint")], requestBody: body("ReplayRequest", { event_id: "evt_…" }), responses: { "200": resp("Replayed") } } },
      "/webhooks/{id}/deliveries": { get: { tags: ["Webhooks"], operationId: "listWebhookDeliveries", summary: "Delivery log", parameters: [idParam("webhook endpoint"), q("limit", "integer", "≤100")], responses: { "200": listResp("Delivery") } } },
      "/settlements": {
        post: { tags: ["Settlements"], operationId: "createSettlement", summary: "Request a settlement", parameters: [idemParam()], requestBody: body("SettlementRequest", { currency: "XAF", amount: "250000", destination: { type: "mobile_money", phone: "+237670123456", name: "Bitbank Ltd" }, reference: "PAYOUT-2026-09" }), responses: { "201": resp("Settlement"), "409": errResp("insufficient_balance"), "422": errResp("settlement_invalid | recipient_invalid") } },
        get: { tags: ["Settlements"], operationId: "listSettlements", summary: "List settlements", responses: { "200": listResp("Settlement") } },
      },
      "/settlements/{id}": { get: { tags: ["Settlements"], operationId: "getSettlement", summary: "Retrieve a settlement", parameters: [idParam("settlement")], responses: { "200": resp("Settlement"), "404": errResp("settlement_not_found") } } },
      "/settlements/{id}/cancel": { post: { tags: ["Settlements"], operationId: "cancelSettlement", summary: "Cancel a requested settlement", parameters: [idParam("settlement"), idemParam()], responses: { "200": resp("Settlement"), "409": errResp("settlement_invalid") } } },
      "/account": { get: { tags: ["Account"], operationId: "getAccount", summary: "Your organization, credential and plan", responses: { "200": resp("Account") } } },
      "/account/balances": { get: { tags: ["Account"], operationId: "getBalances", summary: "Balances", responses: { "200": listResp("Balance") } } },
      "/usage": { get: { tags: ["Account"], operationId: "getUsage", summary: "API usage and volume", parameters: [q("from", "string", "YYYY-MM-DD (default: 30 days ago)"), q("to", "string", "YYYY-MM-DD (default: today)")], responses: { "200": resp("Usage") } } },
      "/transactions": { get: { tags: ["Transactions"], operationId: "listTransactions", summary: "List transactions", parameters: [q("limit", "integer", "≤100")], responses: { "200": listResp("TransactionSummary") } } },
      "/transactions/{id}": { get: { tags: ["Transactions"], operationId: "getTransaction", summary: "Unified timeline: request → quote → payment → rail → payout → ledger → webhooks", parameters: [idParam("payment")], responses: { "200": resp("Transaction") } } },
      "/sandbox/scenarios": { get: { tags: ["Sandbox"], operationId: "listSandboxScenarios", summary: "Reserved recipient numbers that rehearse each outcome", responses: { "200": resp("Scenarios") } } },
      "/sandbox/payments/{id}/pay": { post: { tags: ["Sandbox"], operationId: "sandboxPay", summary: "Simulate the customer paying the instruction", parameters: [idParam("payment")], responses: { "200": resp("Payment") } } },
      "/health": { get: { tags: ["Health"], operationId: "health", security: [], summary: "Service status, supported assets and countries", responses: { "200": resp("Health") } } },
      // ---- MoMo›Me Connect (docs/connect) ----
      "/identities/me": { get: { tags: ["Identities"], operationId: "getMyIdentity", summary: "Your payment identity, aliases, settlement profile and balance", responses: { "200": resp("Identity") } } },
      "/identities": { post: { tags: ["Identities"], operationId: "createIdentity", summary: "Create an identity you manage (branch, sub-merchant, customer)", parameters: [idemParam()], requestBody: body("IdentityRequest", { type: "branch", display_name: "Douala branch", country: "CM", aliases: [{ type: "external_id", value: "BR-DLA-1" }] }), responses: { "201": resp("Identity"), "409": errResp("duplicate_request (alias taken)"), "422": errResp("invalid_identity") } }, get: { tags: ["Identities"], operationId: "listIdentities", summary: "Identities you manage", responses: { "200": listResp("Identity") } } },
      "/identities/{id}": { get: { tags: ["Identities"], operationId: "getIdentity", summary: "An identity (public view unless yours)", parameters: [idParam("identity")], responses: { "200": resp("Identity"), "404": errResp("identity_not_found") } }, patch: { tags: ["Identities"], operationId: "updateIdentity", summary: "Update display name, payment profile, settlement profile", parameters: [idParam("identity")], requestBody: body("IdentityPatch", { settlement: { preferred: "mobile_money", destination: { phone: "+237670123456" } } }), responses: { "200": resp("Identity") } } },
      "/identities/{id}/aliases": { post: { tags: ["Identities"], operationId: "addAlias", summary: "Add an alias (phone, email, merchant_code, external_id…)", parameters: [idParam("identity"), idemParam()], requestBody: body("AliasRequest", { type: "phone", value: "+237677000101" }), responses: { "200": resp("Identity"), "409": errResp("duplicate_request") } } },
      "/identities/{id}/balance": { get: { tags: ["Identities"], operationId: "getIdentityBalance", summary: "MoMo›Me balance of an identity you manage", parameters: [idParam("identity")], responses: { "200": resp("IdentityBalance") } } },
      "/resolve": { post: { tags: ["Identities"], operationId: "resolveParty", summary: "Is this party reachable through MoMo›Me? (privacy-preserving)", requestBody: body("ResolveRequest", { phone: "+237699000202" }), responses: { "200": resp("Resolution"), "429": errResp("rate_limited") } } },
      "/counterparties": { post: { tags: ["Identities"], operationId: "createCounterparty", summary: "A party without a MoMo›Me presence yet", parameters: [idemParam()], requestBody: body("CounterpartyRequest", { name: "Company C", contacts: [{ type: "email", value: "ap@company-c.example" }, { type: "phone", value: "+237655000303" }] }), responses: { "201": resp("Counterparty") } }, get: { tags: ["Identities"], operationId: "listCounterparties", summary: "Your counterparties", responses: { "200": listResp("Counterparty") } } },
      "/payment-intents": { post: { tags: ["Payment intents"], operationId: "createPaymentIntent", summary: "\"Pay 100 000 XAF to Company B\" — the canonical intent", parameters: [idemParam()], requestBody: body("PaymentIntentRequest", { payee: { identity: "mpi_…" }, amount: { value: "100000", currency: "XAF" }, purpose: { type: "invoice", reference: "INV-29381" } }), responses: { "201": resp("PaymentIntent"), "404": errResp("identity_not_found") } }, get: { tags: ["Payment intents"], operationId: "listPaymentIntents", summary: "Your intents", responses: { "200": listResp("PaymentIntent") } } },
      "/payment-intents/{id}": { get: { tags: ["Payment intents"], operationId: "getPaymentIntent", summary: "Retrieve an intent (payment status and settlement status are separate)", parameters: [idParam("intent")], responses: { "200": resp("PaymentIntent") } } },
      "/payment-intents/{id}/execute": { post: { tags: ["Payment intents"], operationId: "executePaymentIntent", summary: "Execute: internal ledger transfer when both parties are connected, else a funding instruction", parameters: [idParam("intent"), idemParam()], requestBody: { required: false, content: { "application/json": { schema: { type: "object", properties: { method: { type: "string", enum: ["momo_me", "lightning", "stablecoin", "mobile_money"] }, payer: { type: "object", properties: { identity: { type: "string" }, phone: { type: "string" } } } } }, example: { method: "lightning" } } } }, responses: { "200": resp("PaymentIntent"), "409": errResp("insufficient_liquidity | payment_failed"), "410": errResp("payment_expired"), "503": errResp("route_unavailable | payment_method_unavailable") } } },
      "/payment-intents/{id}/cancel": { post: { tags: ["Payment intents"], operationId: "cancelPaymentIntent", summary: "Cancel an unfunded intent", parameters: [idParam("intent"), idemParam()], responses: { "200": resp("PaymentIntent") } } },
      "/invoices": { post: { tags: ["Invoices"], operationId: "createInvoice", summary: "Create an invoice, payment link or QR (each owns one intent and a hosted checkout URL)", parameters: [idemParam()], requestBody: body("InvoiceRequest", { kind: "invoice", amount: { value: "45000" }, description: "Order #4471", reference: "ORD-4471", due_date: "2026-10-15", payer: { name: "Someone", phone: "+237655000303" } }), responses: { "201": resp("Invoice") } }, get: { tags: ["Invoices"], operationId: "listInvoices", summary: "Your invoices, links and requests", responses: { "200": listResp("Invoice") } } },
      "/invoices/{id}": { get: { tags: ["Invoices"], operationId: "getInvoice", summary: "Retrieve an invoice", parameters: [idParam("invoice")], responses: { "200": resp("Invoice") } } },
      "/invoices/{id}/cancel": { post: { tags: ["Invoices"], operationId: "cancelInvoice", summary: "Cancel an unpaid invoice", parameters: [idParam("invoice"), idemParam()], responses: { "200": resp("Invoice") } } },
      "/requests": { post: { tags: ["Invoices"], operationId: "createRequestToPay", summary: "Request-to-pay: an invoice with a known payer", parameters: [idemParam()], requestBody: body("InvoiceRequest", { amount: { value: "15000" }, payer: { identity: "mpi_…" }, description: "Rent — October" }), responses: { "201": resp("Invoice"), "422": errResp("invalid_request (payer required)") } } },
      "/payouts": { post: { tags: ["Payouts"], operationId: "createPayout", summary: "Pay out from your balance to a Mobile Money number, a Lightning Address or an identity", parameters: [idemParam()], requestBody: body("PayoutRequest", { amount: { value: "25000" }, destination: { lightning_address: "alice@wallet.com" }, reference: "PAYROLL-09" }), responses: { "201": resp("Payout"), "409": errResp("insufficient_liquidity"), "422": errResp("invalid_identity"), "503": errResp("payment_method_unavailable | route_unavailable") } }, get: { tags: ["Payouts"], operationId: "listPayouts", summary: "Your payouts", responses: { "200": listResp("Payout") } } },
      "/payouts/{id}": { get: { tags: ["Payouts"], operationId: "getPayout", summary: "Retrieve a payout", parameters: [idParam("payout")], responses: { "200": resp("Payout") } } },
      "/checkout/{id}": { get: { tags: ["Checkout"], operationId: "getCheckout", security: [], summary: "Hosted checkout data (public)", parameters: [idParam("intent")], responses: { "200": resp("Checkout") } } },
      "/checkout/{id}/pay": { post: { tags: ["Checkout"], operationId: "checkoutPay", security: [], summary: "Start funding from the hosted checkout (public)", parameters: [idParam("intent")], requestBody: body("CheckoutPayRequest", { method: "lightning", payer_name: "Someone" }), responses: { "200": resp("Checkout") } } },
      "/checkout/{id}/status": { get: { tags: ["Checkout"], operationId: "checkoutStatus", security: [], summary: "Lightweight status poll (public)", parameters: [idParam("intent")], responses: { "200": resp("CheckoutStatus") } } },
    },
    webhooks: Object.fromEntries(EVENT_TYPES.map((t) => [t, { post: { summary: t, description: "Signed `POST` to your endpoint. Verify `X-MoMoMe-Signature` (`t=<unix-ms>,v1=<hex hmac-sha256(secret, t + '.' + rawBody)>`) and de-duplicate on `X-MoMoMe-Event-Id`. Reply 2xx within 10 s; otherwise we retry with backoff (1 s, 10 s, 1 min, 10 min, 1 h) then dead-letter (replayable).", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/Event" } } } }, responses: { "200": { description: "Acknowledged" } } } }])),
    components: {
      securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "mm_live_… / mm_test_…", description: "`Authorization: Bearer <credential>`. Create credentials in the developer dashboard." } },
      schemas: {
        Meta: { type: "object", properties: { request_id: { type: "string", example: "req_5f1c9e2ab3d94c7e" } } },
        Error: { type: "object", properties: { error: { type: "object", properties: { code: { type: "string", example: "quote_expired" }, message: { type: "string" }, details: { type: "object", additionalProperties: true } }, required: ["code", "message"] }, meta: { $ref: "#/components/schemas/Meta" } }, example: err("quote_expired", "This quote has expired. Create a new quote.") },
        QuoteRequest: { type: "object", required: ["source", "destination"], properties: { source: { type: "object", required: ["asset"], properties: { asset: { type: "string", enum: ["BTC", "USDT", "USDC"] }, network: { type: "string", enum: ["LIGHTNING", "BITCOIN", "ETHEREUM"] }, amount: { type: "string", description: "Amount of the asset to send (give this OR destination.amount)" } } }, destination: { type: "object", required: ["country"], properties: { country: { type: "string", example: "CM" }, currency: { type: "string", example: "XAF" }, amount: { type: "string", description: "XAF to deliver" }, phone: { type: "string", description: "E.164; validated now, used as the default recipient" } } } } },
        Quote: { type: "object", properties: { id: { type: "string" }, object: { const: "quote" }, status: { type: "string", enum: ["active", "expired", "used"] }, source: { type: "object", properties: { asset: { type: "string" }, network: { type: "string" }, amount: { type: "string" } } }, destination: { type: "object", properties: { country: { type: "string" }, currency: { type: "string" }, amount: { type: "string" } } }, rate: { type: "object", properties: { pair: { type: "string" }, value: { type: "string" }, spread_bps: { type: "integer" }, locked_until: { type: "string" }, estimate_only: { type: "boolean" } } }, fees: { type: "object", properties: { platform: money("Platform fee"), network: { type: "object" }, payout: money("Payout fee"), provider: money("Provider fee"), total: money("Total fees") } }, total_cost: { type: "object" }, usd_equivalent: { type: "string" }, created_at: { type: "string" }, expires_at: { type: "string" } } },
        PaymentRequest: { type: "object", required: ["quote_id", "recipient"], properties: { quote_id: { type: "string" }, reference: { type: "string", maxLength: 64, description: "Your own id; unique per organization" }, recipient: { type: "object", required: ["phone"], properties: { phone: { type: "string", description: "E.164" }, name: { type: "string", description: "Who you expect; compared to the operator's record" } } }, metadata: { type: "object", additionalProperties: { type: "string" }, maxProperties: 20 }, confirmation_token: { type: "string", description: "From a 409 recipient_unverified response, to confirm the recipient" } } },
        Payment: { type: "object", properties: { id: { type: "string" }, object: { const: "payment" }, reference: { type: ["string", "null"] }, status: { type: "string", enum: ["CREATED", "AWAITING_PAYMENT", "PAYMENT_DETECTED", "PAYMENT_CONFIRMED", "CONVERSION_PROCESSING", "PAYOUT_PROCESSING", "PAYOUT_SUBMITTED", "COMPLETED", "EXPIRED", "FAILED", "CANCELLED", "REFUNDED", "MANUAL_REVIEW"] }, quote_id: { type: "string" }, source: { type: "object" }, destination: { type: "object" }, recipient: { type: "object", properties: { phone: { type: "string" }, operator: { type: "string" }, name: { type: ["string", "null"] }, name_verified: { type: "boolean" } } }, fees: { type: "object" }, payment_instructions: { type: ["object", "null"], properties: { method: { type: "string", enum: ["lightning_invoice", "bitcoin_address", "erc20_address"] }, asset: { type: "string" }, network: { type: "string" }, amount: { type: "string" }, code: { type: "string", description: "The invoice or address to pay" }, uri: { type: "string", description: "Payment URI for a QR" }, expires_at: { type: "string" } } }, refund: { type: ["object", "null"] }, failure: { type: ["object", "null"] }, metadata: { type: "object" }, expires_at: { type: ["string", "null"] }, timeline: { type: "object", properties: Object.fromEntries(["created_at", "quote_created_at", "payment_detected_at", "payment_confirmed_at", "conversion_started_at", "payout_started_at", "payout_submitted_at", "payout_completed_at", "completed_at", "failed_at"].map((k) => [k, { type: ["string", "null"] }])) }, created_at: { type: "string" }, updated_at: { type: "string" }, livemode: { type: "boolean" } } },
        RefundRequest: { type: "object", properties: { destination: { type: "object", properties: { asset: { const: "BTC" }, network: { const: "LIGHTNING" }, invoice: { type: "string" } } } } },
        RecipientValidateRequest: { type: "object", required: ["phone"], properties: { phone: { type: "string" }, country: { type: "string" }, name: { type: "string" } } },
        RecipientValidation: { type: "object", properties: { phone: { type: "string" }, country: { type: "string" }, currency: { type: "string" }, valid: { type: "boolean" }, reason: { type: "string" }, operator: { type: ["string", "null"] }, name: { type: ["string", "null"] }, name_status: { type: "string", enum: ["verified_by_operator", "verified_by_momome", "unknown", "not_checked"] }, name_match: { type: "string", enum: ["match", "mismatch", "not_available"] } } },
        WebhookRequest: { type: "object", required: ["url"], properties: { url: { type: "string" }, events: { type: "array", items: { type: "string", enum: [...EVENT_TYPES, "*"] } }, description: { type: "string" } } },
        WebhookPatch: { type: "object", properties: { url: { type: "string" }, events: { type: "array", items: { type: "string" } }, enabled: { type: "boolean" }, description: { type: "string" } } },
        WebhookEndpoint: { type: "object", properties: { id: { type: "string" }, object: { const: "webhook_endpoint" }, url: { type: "string" }, events: { type: "array", items: { type: "string" } }, enabled: { type: "boolean" }, description: { type: ["string", "null"] }, secret_hint: { type: "string" }, consecutive_failures: { type: "integer" }, created_at: { type: "string" } } },
        WebhookEndpointWithSecret: { allOf: [{ $ref: "#/components/schemas/WebhookEndpoint" }, { type: "object", properties: { secret: { type: "string", description: "Shown once" } } }] },
        Delivery: { type: "object", properties: { event_id: { type: "string" }, type: { type: "string" }, status: { type: "string", enum: ["pending", "delivered", "dead"] }, attempts: { type: "integer" }, last_http_status: { type: ["integer", "null"] }, last_error: { type: ["string", "null"] }, next_attempt_at: { type: ["string", "null"] }, event: { $ref: "#/components/schemas/Event" } } },
        Event: { type: "object", properties: { id: { type: "string", example: "evt_…" }, object: { const: "event" }, type: { type: "string", enum: [...EVENT_TYPES, "ping"] }, created_at: { type: "string" }, livemode: { type: "boolean" }, data: { type: "object", description: "The Payment or Settlement" } } },
        ReplayRequest: { type: "object", required: ["event_id"], properties: { event_id: { type: "string" } } },
        SettlementRequest: { type: "object", required: ["amount", "destination"], properties: { currency: { const: "XAF" }, amount: { type: "string" }, destination: { type: "object", properties: { type: { type: "string", enum: ["mobile_money", "bank"] }, phone: { type: "string" }, name: { type: "string" }, bank: { type: "string" }, account: { type: "string" } } }, reference: { type: "string" } } },
        Settlement: { type: "object", properties: { id: { type: "string" }, object: { const: "settlement" }, status: { type: "string", enum: ["REQUESTED", "PROCESSING", "SUBMITTED", "COMPLETED", "FAILED", "CANCELLED"] }, currency: { type: "string" }, amount: { type: "string" }, fee: { type: "string" }, net_amount: { type: "string" }, destination: { type: "object" }, reference: { type: ["string", "null"] }, provider_reference: { type: ["string", "null"] }, requested_at: { type: "string" }, completed_at: { type: ["string", "null"] }, livemode: { type: "boolean" } } },
        Account: { type: "object", properties: { organization: { type: "object" }, application: { type: "object" }, credential: { type: "object" }, plan: { type: "object" }, environment: { type: "string" }, livemode: { type: "boolean" } } },
        Balance: { type: "object", properties: { currency: { type: "string" }, available: { type: "string" }, pending_settlement: { type: "string" } } },
        Usage: { type: "object", properties: { from: { type: "string" }, to: { type: "string" }, requests: { type: "integer" }, quotes: { type: "integer" }, payments: { type: "integer" }, completed: { type: "integer" }, failed: { type: "integer" }, volumeXaf: { type: "integer" }, feesXaf: { type: "integer" }, successRatePct: { type: "integer" }, avgLatencyMs: { type: "integer" }, days: { type: "array", items: { type: "object" } } } },
        TransactionSummary: { type: "object", properties: { id: { type: "string" }, reference: { type: ["string", "null"] }, status: { type: "string" }, amount: { type: "string" }, currency: { type: "string" }, source_asset: { type: "string" }, created_at: { type: "string" } } },
        Transaction: { type: "object", properties: { id: { type: "string" }, status: { type: "string" }, payment: { $ref: "#/components/schemas/Payment" }, compliance: { type: ["object", "null"] }, steps: { type: "array", items: { type: "object", properties: { at: { type: "string" }, step: { type: "string" }, detail: { type: "string" } } } }, ledger: { type: "array", items: { type: "object" } }, webhooks: { type: "array", items: { type: "object" } } } },
        Scenarios: { type: "object", properties: { data: { type: "array", items: { type: "object", properties: { phone: { type: "string" }, scenario: { type: "string" } } }, example: SCENARIO_NUMBERS } } },
        Health: { type: "object", properties: { status: { type: "string" }, environment: { type: "string" }, version: { type: ["string", "null"] }, assets: { type: "array" }, countries: { type: "array" }, payout_providers: { type: "array" } } },
        Deleted: { type: "object", properties: { id: { type: "string" }, deleted: { type: "boolean" } } },
        Identity: { type: "object", properties: { id: { type: "string", example: "mpi_…" }, object: { const: "identity" }, type: { type: "string" }, display_name: { type: "string" }, country: { type: "string" }, status: { type: "string" }, aliases: { type: "array", items: { type: "object", properties: { type: { type: "string" }, value: { type: "string" }, verified: { type: "boolean" } } } }, payment_methods: { type: "array", items: { type: "string" } }, capabilities: { type: "array", items: { type: "string" } }, lightning_enabled: { type: "boolean" }, settlement: { type: "object", description: "Owner view only" }, balance: { type: "object" } } },
        IdentityRequest: { type: "object", required: ["display_name"], properties: { type: { type: "string" }, display_name: { type: "string" }, country: { type: "string" }, aliases: { type: "array", items: { type: "object", properties: { type: { type: "string" }, value: { type: "string" } } } }, settlement: { type: "object" } } },
        IdentityPatch: { type: "object", properties: { display_name: { type: "string" }, payment_profile: { type: "object" }, settlement: { type: "object", properties: { preferred: { type: "string", enum: ["momo_me", "mobile_money", "bank_transfer", "lightning"] }, destination: { type: "object" } } } } },
        AliasRequest: { type: "object", required: ["type", "value"], properties: { type: { type: "string", enum: ["phone", "email", "merchant_code", "lightning_address", "api_recipient_id", "external_id"] }, value: { type: "string" } } },
        IdentityBalance: { type: "object", properties: { identity: { type: "string" }, currency: { type: "string" }, available: { type: "string" } } },
        ResolveRequest: { type: "object", properties: { phone: { type: "string" }, email: { type: "string" }, lightning_address: { type: "string" }, merchant_code: { type: "string" }, business_id: { type: "string" }, identity: { type: "string" }, country: { type: "string" } } },
        Resolution: { type: "object", properties: { reachable: { type: "boolean" }, identity: { type: "string" }, identity_type: { type: ["string", "null"] }, display_name: { type: ["string", "null"] }, connected: { type: "boolean" }, payment_capabilities: { type: "array", items: { type: "string" } }, lightning_address: { type: ["string", "null"] } } },
        CounterpartyRequest: { type: "object", required: ["name", "contacts"], properties: { name: { type: "string" }, contacts: { type: "array", items: { type: "object", properties: { type: { type: "string" }, value: { type: "string" } } } }, metadata: { type: "object" } } },
        Counterparty: { type: "object", properties: { id: { type: "string" }, name: { type: "string" }, contacts: { type: "array" }, linked_identity: { type: ["string", "null"] }, created_at: { type: "string" } } },
        PaymentIntentRequest: { type: "object", required: ["amount"], properties: { payee: { type: "object", properties: { identity: { type: "string" } } }, payer: { type: "object", properties: { identity: { type: "string" }, counterparty: { type: "string" }, phone: { type: "string" }, name: { type: "string" } } }, amount: { type: "object", properties: { value: { type: "string" }, currency: { type: "string" } } }, purpose: { type: "object" }, permitted_methods: { type: "array", items: { type: "string" } }, ttl_seconds: { type: "integer" }, metadata: { type: "object" }, callback_url: { type: "string" } } },
        PaymentIntent: { type: "object", properties: { id: { type: "string" }, object: { const: "payment_intent" }, status: { type: "string", enum: ["created", "authorized", "pending", "processing", "completed", "failed", "expired", "reversed"] }, settlement_status: { type: "string", enum: ["not_applicable", "pending", "processing", "settled", "failed", "reversed"] }, surface: { type: "string" }, payee: { type: "object" }, payer: { type: "object" }, amount: { type: "object" }, purpose: { type: "object" }, permitted_methods: { type: "array" }, settlement: { type: "object" }, route: { type: ["object", "null"] }, execution: { type: ["object", "null"], description: "kind, method, payment_id, payment_instructions" }, checkout_url: { type: "string" }, invoice_id: { type: ["string", "null"] }, expires_at: { type: "string" }, livemode: { type: "boolean" } } },
        InvoiceRequest: { type: "object", required: ["amount"], properties: { kind: { type: "string", enum: ["invoice", "payment_link", "qr"] }, amount: { type: "object" }, description: { type: "string" }, reference: { type: "string" }, due_date: { type: "string" }, payer: { type: "object" }, accepted_methods: { type: "array", items: { type: "string" } }, metadata: { type: "object" }, callback_url: { type: "string" } } },
        Invoice: { type: "object", properties: { id: { type: "string" }, object: { const: "invoice" }, number: { type: "string" }, kind: { type: "string" }, status: { type: "string", enum: ["draft", "issued", "pending", "paid", "expired", "cancelled", "refunded"] }, payee: { type: "object" }, payer: { type: ["object", "null"] }, amount: { type: "object" }, description: { type: ["string", "null"] }, reference: { type: ["string", "null"] }, due_date: { type: ["string", "null"] }, accepted_methods: { type: "array" }, partial_payments: { const: false }, payment_intent: { type: "string" }, payment_url: { type: "string" }, qr: { type: "object" }, paid_at: { type: ["string", "null"] }, livemode: { type: "boolean" } } },
        PayoutRequest: { type: "object", required: ["amount", "destination"], properties: { source: { type: "object", properties: { identity: { type: "string" } } }, amount: { type: "object" }, destination: { type: "object", properties: { phone: { type: "string" }, country: { type: "string" }, lightning_address: { type: "string" }, identity: { type: "string" }, name: { type: "string" } } }, reference: { type: "string" }, metadata: { type: "object" } } },
        Payout: { type: "object", properties: { id: { type: "string" }, object: { const: "payout" }, status: { type: "string", enum: ["created", "processing", "completed", "failed", "reversed"] }, payer: { type: "object" }, amount: { type: "object" }, fee: { type: "object" }, destination: { type: "object" }, provider_reference: { type: ["string", "null"] }, failure_reason: { type: ["string", "null"] }, reference: { type: ["string", "null"] }, created_at: { type: "string" }, completed_at: { type: ["string", "null"] }, livemode: { type: "boolean" } } },
        Checkout: { type: "object", properties: { id: { type: "string" }, status: { type: "string" }, settlement_status: { type: "string" }, payee: { type: "object" }, amount: { type: "object" }, purpose: { type: "object" }, methods: { type: "array", items: { type: "string" } }, execution: { type: ["object", "null"] }, expires_at: { type: "string" }, livemode: { type: "boolean" } } },
        CheckoutPayRequest: { type: "object", required: ["method"], properties: { method: { type: "string", enum: ["lightning", "stablecoin", "mobile_money"] }, payer_phone: { type: "string" }, payer_name: { type: "string" } } },
        CheckoutStatus: { type: "object", properties: { id: { type: "string" }, status: { type: "string" }, settlement_status: { type: "string" }, has_instruction: { type: "boolean" } } },
        Sent: { type: "object", properties: { sent: { type: "boolean" }, event_ids: { type: "array", items: { type: "string" } } } },
        Replayed: { type: "object", properties: { replayed: { type: "boolean" }, event_id: { type: "string" } } },
      },
    },
  };
}
function idemParam() { return { name: "Idempotency-Key", in: "header", required: true, schema: { type: "string", maxLength: 255 }, description: "Unique per request intent; retries with the same key and body replay the original response." }; }
function idParam(what: string) { return { name: "id", in: "path", required: true, schema: { type: "string" }, description: `The ${what} id` }; }
function q(name: string, type: string, description: string) { return { name, in: "query", required: false, schema: { type }, description }; }
function body(schema: string, example: unknown) { return { required: true, content: { "application/json": { schema: { $ref: `#/components/schemas/${schema}` }, example } } }; }
function resp(schema: string) { return { description: "OK", content: { "application/json": { schema: { type: "object", properties: { data: { $ref: `#/components/schemas/${schema}` }, meta: { $ref: "#/components/schemas/Meta" } } } } } }; }
function listResp(schema: string) { return { description: "OK", content: { "application/json": { schema: { type: "object", properties: { data: { type: "object", properties: { object: { const: "list" }, data: { type: "array", items: { $ref: `#/components/schemas/${schema}` } }, has_more: { type: "boolean" }, next_cursor: { type: "string" } } }, meta: { $ref: "#/components/schemas/Meta" } } } } } }; }
function errResp(codes: string) { return { description: codes, content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }; }
